version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Cambié aquí
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app_network

  api1:
    build: ./services/kafka-producer  # Directorio donde está el Dockerfile de la primera API
    container_name: producer
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - app_network

  api2:
    build: ./services/kafka-consumer  # Directorio donde está el Dockerfile de la segunda API
    container_name: consumer
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - app_network

networks:
  app_network:
    driver: bridge