spring:
  application:
    name: kafka-producer

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1  # Garantiza que Kafka confirma la recepción del mensaje

    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true  # Habilita la confirmación automática del offset

server:
  port: 8080
  address: 0.0.0.0
springdoc:
  swagger-ui:
    path: /documentacion.html
